from Vehicle import Vehicle
from Ship import Ship
from Airplane import Airplane

#dummy data for vehicles
print("=========== Vehicle ===========")
v1 = Vehicle()
v1.setName("Car")
v1.setFuel("Solar")
v1.setPassengers(2)
v1.print()

v2 = Vehicle()
v2.setName("Bike")
v2.setFuel("Gasoline")
v2.setPassengers(2)
print("")
v2.print()

v3 = Vehicle()
v3.setName("Bycicle")
v3.setFuel("None")
v3.setPassengers(1)
print("")
v3.print()

v4 = Vehicle()
v4.setName("Plane")
v4.setFuel("Kerosene")
v4.setPassengers(80)
print("")
v4.print()

v5 = Vehicle()
v5.setName("Bus")
v5.setFuel("Solar")
v5.setPassengers(50)
print("")
v5.print()

#dummy data for Ships
print("")
print("============= Ship =============")
s1 = Ship()
s1.setName("Tampomas")
s1.setFuel("Diesel")
s1.setPassengers(1500)
s1.setAge(15)
s1.setCountry("Japan")
s1.setType("Cruise Ship")
print("")
s1.print()

s2 = Ship()
s2.setName("Titanic")
s2.setFuel("Diesel")
s2.setPassengers(2500)
s2.setAge(25)
s2.setCountry("Ireland")
s2.setType("Cruise")
print("")
s2.print()

s3 = Ship()
s3.setName("Marina")
s3.setFuel("Diesel")
s3.setPassengers(300)
s3.setAge(5)
s3.setCountry("Indonesia")
s3.setType("Ferry")
print("")
s3.print()

s4 = Ship()
s4.setName("Ketek")
s4.setFuel("Gasoline")
s4.setPassengers(8)
s4.setAge(6)
s4.setCountry("Indonesia")
s4.setType("Armchair Boat")
print("")
s4.print()

s5 = Ship()
s5.setName("Musashi")
s5.setFuel("Diesel")
s5.setPassengers(18)
s5.setAge(11)
s5.setCountry("America")
s5.setType("Yacht")
print("")
s5.print()

#dummy data for airplanes
print("")
print("============ Planes ============")
p1 = Airplane()
p1.setName("BOEING 737")
p1.setType("Composite Airliner")
p1.setFuel("Kerosene")
p1.setAge(14)
p1.setPassengers(80)
p1.setWingspan("117 ft 5 in")
print("")
p1.print()

p2 = Airplane()
p2.setName("Blériot XI")
p2.setType("Tractor Monoplane")
p2.setFuel("Gasoline")
p2.setAge(113)
p2.setPassengers(1)
p2.setWingspan("28 ft 6 in")
print("")
p2.print()

p3 = Airplane()
p3.setName("Supermarine Spitfire")
p3.setType("Performance Interceptor Aircraft")
p3.setFuel("Diesel")
p3.setAge(86)
p3.setPassengers(1)
p3.setWingspan("36 ft 10 in")
print("")
p3.print()

p4 = Airplane()
p4.setName("Lockheed SR-71 Blackbird")
p4.setType("Strategic Reconnaissance Aircraft")
p4.setFuel("Kerosene")
p4.setAge(56)
p4.setPassengers(1)
p4.setWingspan("55 ft 6 in")
print("")
p4.print()

p5 = Airplane()
p5.setName("Learjet 23")
p5.setType("Business Jet")
p5.setFuel("Kerosene")
p5.setAge(59)
p5.setPassengers(8)
p5.setWingspan("35 ft 7 in")
print("")
p5.print()